sevices:
  - docker

before_install:
    - TAG=$(git tag --contains $TRAVIS_COMMIT)
    - SHORT_COMMIT=$(git rev-parse --short $TRAVIS_COMMIT)
    - VERSION=${TAG:-$SHORT_COMMIT}
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.gitlab.com
    - docker build -t registry.gitlab.com/klinki/docker-registry/pse:latest .
    - docker build -t registry.gitlab.com/klinki/docker-registry/pse:${VERSION} .
    - docker push registry.gitlab.com/klinki/docker-registry/pse:latest
    - docker push registry.gitlab.com/klinki/docker-registry/pse:${VERSION}

# deploy:
#    - cat ./deploy.sh | ssh ${DEPLOY_USER}@${DEPLOY_SERVER}
#    - echo "Deploy finished"
