language: minimal
sevices:
  - docker

before_install:
    - openssl aes-256-cbc -K $encrypted_699ce602e140_key -iv $encrypted_699ce602e140_iv
        -in deploy_key.enc -out deploy_key -d
    - chmod 600 ./deploy_key
    - echo -e "Host cloud.inviser.cz\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - echo -e "Host inviser.cz\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

    - TAG=$(git tag --contains $TRAVIS_COMMIT)
    - SHORT_COMMIT=$(git rev-parse --short $TRAVIS_COMMIT)
    - VERSION=${TAG:-$SHORT_COMMIT}
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.gitlab.com
    - docker build
      -t registry.gitlab.com/klinki/docker-registry/pse:latest
      -t registry.gitlab.com/klinki/docker-registry/pse:${VERSION}
      --build-arg VERSION=${VERSION}
      --build-arg SHORT_COMMIT=${SHORT_COMMIT}
      .
    - docker push registry.gitlab.com/klinki/docker-registry/pse:latest
    - docker push registry.gitlab.com/klinki/docker-registry/pse:${VERSION}

after_success:
    - cat ./deploy.sh | ssh -i ./deploy_key ${DEPLOY_USER}@${DEPLOY_SERVER}
    - echo "Deploy finished"
